      - name: Copy charts into docs for Pages and build index
        run: |
          mkdir -p docs/charts
          # Copy generated SVGs
          cp -f public/charts/*.svg docs/charts/ 2>/dev/null || true

          # Create a simple index.html
          {
            echo '<!doctype html>'
            echo '<html lang="en"><head><meta charset="utf-8" />'
            echo '<meta name="viewport" content="width=device-width, initial-scale=1" />'
            echo '<title>Housing Charts</title>'
            echo '<style>body{font-family:system-ui,Segoe UI,Roboto,Arial} .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px}</style>'
            echo '</head><body>'
            echo '<h1>Housing Burden Charts</h1>'
            echo '<div class="grid">'
            for f in docs/charts/*.svg; do
              [ -e "$f" ] || continue
              name="$(basename "$f")"
              echo "<div><a href='charts/$name'>$name</a></div>"
            done
            echo '</div></body></html>'
          } > docs/index.html

      - name: Show what will be published
        run: |
          echo "---- docs/"
          ls -la docs
          echo "---- docs/charts/"
          ls -la docs/charts || true

      - name: Commit and push changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/** || true
            git commit -m "docs: publish latest charts and index for GitHub Pages [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi