name: Generate housing burden charts

on:
  push:
    paths:
      - '**.py'
      - requirements.txt
      - .github/workflows/generate_charts.yml
  workflow_dispatch:          # run manually from the Actions tab
  schedule:
    - cron: "0 12 * * 1"      # Mondays 12:00 UTC (~8 AM ET)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # needed to push changes back to the repo

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate API env & generate charts
        env:
          API_FROM_SECRET: ${{ secrets.API_URL }}
          API_FROM_VAR: ${{ vars.API_URL }}
        run: |
          # Prefer secret; fall back to repo variable
          API="${API_FROM_SECRET:-$API_FROM_VAR}"
          if [ -z "$API" ]; then
            echo "ERROR: API env var is missing. Set secrets.API_URL or vars.API_URL."
            exit 1
          fi
          export API
          python generate_charts.py

      - name: Build index.html for charts
        run: |
          mkdir -p docs/charts

          # Build index.html with a heredoc (avoids quoting issues)
          cat > docs/index.html <<'HTML'
          <!doctype html>
          <html lang="en">
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <title>Housing Burden Charts</title>
              <style>
                body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Arial;margin:20px}
                .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px}
                a{word-break:break-all}
                .muted{color:#666}
              </style>
            </head>
            <body>
              <h1>Housing Burden Charts</h1>
              <p class="muted">Auto-generated by GitHub Actions. Click a file to view the chart.</p>
              <div class="grid">
          HTML

          # Add each chart link (both SVGs and PNGs)
          for f in docs/charts/*.{svg,png}; do
            [ -e "$f" ] || continue
            name="$(basename "$f")"
            echo "<div><a href='charts/$name'>$name</a></div>" >> docs/index.html
          done

          echo "    </div></body></html>" >> docs/index.html

      - name: Show what will be published
        run: |
          echo "---- docs/"
          ls -la docs || true
          echo "---- docs/charts/"
          ls -la docs/charts || true

      - name: Commit and push docs (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/**
            git commit -m "docs: publish latest charts and index for GitHub Pages [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi