name: Generate housing burden charts

on:
  workflow_dispatch:  # run from Actions tab
  schedule:
    - cron: "0 12 * * 1"  # Mondays 12:00 UTC (~8 AM ET)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate API env & generate charts
        env:
          API: ${{ secrets.API_URL || vars.API_URL}}
        run: |
          python generate_charts.py

      - name: Copy charts into docs for Pages (static page link) from github
        run: |
          mkdir -p docs/charts
          cp -f public/charts/*.svg docs/charts/ || true
          echo '<h1>Housing Charts</h1><ul>' > docs/index.html
          for f in docs/charts/*.svg; do
            name=$(basename "$f")
            echo <li><a href='charts/$name'>$name</a></li>" >> docs/index.html
          done
          echo '</ul>' >> docs/index.html
      - name: Commit and push changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/charts/*.svg || true
            git commit -m "chore(charts): update generated SVGs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
